name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile document
        uses: xu-cheng/latex-action@v3
        with:
          compiler: latexmk
          root_file: main.tex
          latexmk_shell_escape: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
